stages:
- test
- build

before_script:
- mkdir -p $GOPATH/src/github.com/RaveNoX/
- ln -s $(pwd) $GOPATH/src/github.com/RaveNoX/go-jsonmerge
- cd $GOPATH/src/github.com/RaveNoX/go-jsonmerge
- go get
- (cd cmd/jsonmerge && go get)

after_script:
- rm $GOPATH/src/github.com/RaveNoX/go-jsonmerge

format:
    tags:
    - docker
    - linux
    image: golang:latest
    stage: test
    script:
    - go get -u golang.org/x/tools/cmd/goimports
    # If formatted is different than committed, exit with error    
    - (if [ "$(goimports -l ./)" == "" ]; then echo "Good format"; else echo "Bad format"; exit 33; fi);

test:
    tags:
    - docker
    - linux
    image: golang:latest
    stage: test
    script:
    - pwd
    - go test -cover -v ./...

compile-linux:
    tags:
    - docker
    - linux
    image: golang:latest
    stage: build
    variables:
        GOOS: linux
        GOARCH: amd64
    script:    
    - mkdir -p artifacts
    - go build -o artifacts/jsonmerge ./cmd/jsonmerge 
    artifacts:
        paths:
        - artifacts/*

compile-windows:
    tags:
    - docker
    - linux
    image: golang:latest
    stage: build
    variables:
        GOOS: windows
        GOARCH: amd64
    script:
    - mkdir -p artifacts    
    - go build -o artifacts/jsonmerge.exe ./cmd/jsonmerge
    artifacts:
        paths:
        - artifacts/*

